<?php
namespace phone\controllers;
use phone\models\User;
use yii\helpers\Json;


/**
 * Site controller
 */
class UserController extends CommonController
{
    /**
     * Displays homepage.
     *
     * @return string
     */

    public function beforeAction($action)
    {
        $user_id = \Yii::$app->request->get('id');
        $user_id = isset($user_id) ? $user_id : '';
        //如果不是超级管理员并且 info路由的参数id不能为用户登录的id
        if(\Yii::$app->view->params['userInfo']['type'] != 1 && $user_id != \Yii::$app->user->id){
            echo '您还不是超级管理员'; die;
        };
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        //读数据
        $params = \Yii::$app->request->get();
        if(\Yii::$app->request->isAjax){
            $user = User::search($params);
            return $this->convertJson('0','查询成功',$user['list'], $user['count']);
        }
        return $this->render('index');
    }

    public function actionInfo(){
        $user_id = \Yii::$app->request->get('id');
        $message = '添加成功';
        $url = '/user';
        if($user_id){
            $message = '修改成功';
        }
        if($user_id && !User::findOne($user_id)){
            return '用户ID不存在...';
        }
        if(\Yii::$app->view->params['userInfo']['type'] != 1){
            $url = '/console';
        }

        if(\Yii::$app->request->isPost){
            $params = \Yii::$app->request->post();
            if(User::insetUpdate($params,$user_id)){
                return Json::encode(array('code'=>100000,'message'=>$message,'url'=>$url));
            }
            return Json::encode(array('code'=>100001,'message'=>'添加失败','url'=>$url));
        }

        $userInfo = User::find()->where(['id'=>$user_id])->asArray()->one();
        return $this->render('info',compact('userInfo'));
    }

    public function actionDelete(){
        $user_id = \Yii::$app->request->post('id');
        $user_id = isset($user_id) ? $user_id : '';
        if(\Yii::$app->request->isPost){
            User::deleteAll(['id'=>$user_id]);
            return Json::encode(array('code'=>100000,'message'=>'删除成功'));
        }
    }
}